### ISSUE TITLE
Get rid of object-assign ponyfill

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#135]
Since we upgrated to Node 6, `Object.assign` is there already. So there is no need for `object-assign` ponyfill. All usages of `objectAssign` can now be replaced with `Object.assign`.

**Comment by BrainMaestro** [comment]
Can I pick this up?

**Comment by ro31337** [comment]
@BrainMaestro sure! thanks for your commit, I'll check it asap and merge.
