### ISSUE TITLE
Add Persian translation json file

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#424]
Add Persian language translation. Original author: `@MR5857` in Telegram. Here is the translation itself https://gist.github.com/ro31337/ed182538dbebd62f9f99bb3315738e83

Unfortunately, I have no skills with editing right-to-left text, and I don't know how GitHub and Telegram handles it (I assume it handles OK).

So in this story do the following:

* Check translation by comparing keys to English: https://github.com/ro31337/libretaxi/blob/master/locales/en.json
* Pay attention to `passenger-contact-new-number.message` and `passenger-contact-driver-price.message` - there is information that translation can be incorrect because GitHub doesn't support (?) right-to-left text (?).
* Make sure strings containing `%s`, `{{something}}` spelled correctly and there are no unicode characters between them (otherwise string interpolation will fail).
* Make sure _all_ icons are in place. For example, when I type "🚗 ماشین" into google translate, I get the following:

![image](https://cloud.githubusercontent.com/assets/1477672/22234908/a1781fa6-e1b0-11e6-9634-fbd99c3588fe.png)

It seems right, in Persian icon is at the beginning (at the end visually). However, in json file it's at the end (at the beginning visually).

In Telegram it also seems right (when you paste "🚗 ماشین" without quotes, you get exactly what is expected):

![image](https://cloud.githubusercontent.com/assets/1477672/22234975/2f54151e-e1b1-11e6-98b7-e07bf985b7d9.png)

The translation above can be technically correct, just attention from someone familiar with Git and Persian language is required.

So In this story:

* Do all the checks written above
* Add Persian translation file and create PR (you can create PR to the `master` branch, it's OK for this story)
* In PR message **verbosely explain** what has been done, give as much information as it is possible.

This issue is high priority one and Persian-speaking community is looking forward to use the bot. Please help the world to be a better place by working on this issue.

**Comment by efazati** [comment]
Is there this file in repo? https://gist.github.com/ro31337/ed182538dbebd62f9f99bb3315738e83

**Comment by ro31337** [comment]
Not yet, on the way. However, if you feel enthusiastic, consider translating `index.html` to Persian here: https://github.com/ro31337/libretaxi-www/issues/17
