### ISSUE TITLE
Add support for Bitcoin payments

### ISSUE THREAD

**Issue by underyx** [ro31337/libretaxi#429]
I'd love to use libretaxi, but there's just no way I'll go out of my way to get cash to use it.

I see that Bitcoin support is planned, but apparently there was no issue yet to track this feature, so, here ya go!

**Comment by nacimux** [comment]
Hi, I can help on this issue, any plan to start ? @underyx

**Comment by underyx** [comment]
@nacimux no, I had no plans to develop it.

**Comment by nacimux** [comment]
@underyx  What do you think to start by choosing a Bitcoin payment gateway?  i'am taking a look at [https://bitpay.com](url).

**Comment by underyx** [comment]
@nacimux I'm not very well-versed in the current state of Bitcoin gateways. I'm not even sure yet how the integration would work; wouldn't each driver have to register as a sort of 'business entity' at the gateway and then set it up themselves? At this point, wouldn't it be reasonable to launch Bitcoin support with some very quick, simple, and dirty hack like:

1. just showing the driver's hardcoded Bitcoin address on the rider's side with a payment URI
2. matching riders to drivers with taking the available payment methods into account

**Comment by rocketinventor** [comment]
@nacimux Your comment shows a lack of understanding of how bitcoin works. There is no need for a bitcoin gateway because everything is already peer 2 peer. Simply showing a barcode and/or a wallets public key as @underyx said is much simpler, and is enough to make a transaction.

**Comment by nacimux** [comment]
@rocketinventor  @underyx great ! ok.

**Comment by rocketinventor** [comment]
Later on, it might be nice to implement something like #458.

**Comment by capaj** [comment]
BTC has outrageous fees- in poorer countries a ride can be very cheap, but the BTC fee would be an obstacle few would be willing to deal with.
Wouldn't it make more sense to implement IOTA payments? It would be quite trivial using their official JS lib: https://github.com/iotaledger/iota.lib.js

Ideally we could get more than one crypto currency support, but if I had to choose one, IOTA is the most fitting.

**Comment by ro31337** [comment]
@capaj what is IOTA btw? I can read definition on their website, but it doesn't make too much sense for me. How would you describe that?

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
