### ISSUE TITLE
More payment solutions

### ISSUE THREAD

**Issue by kedoska** [ro31337/libretaxi#436]
Considering each driver as a single "company", is it a bad idea allowing them to set up their own payment integration?

### CC Payment Gateway or/and E-wallets
there are many available payment gateway that can provide only API. Having the platform integrated with them (some of them) can allows drivers to set up their merchant accounts. Development can be done on _sandboxes_.

A possible scenario is the driver that is presented with a "Payments Integration Panel" where, available methods for his/her country are listed.

**Comment by dessalines** [comment]
The best would be paypal direct pay, so people could just use their credit cards to pay others directly.

**Comment by uber1geek** [comment]
I would also suggest PayTM , a very popular mobile wallet for India.

**Comment by rocketinventor** [comment]
If payments are with BC, only a wallet public key is needed.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
