### ISSUE TITLE
What's the profit for the server owner?

### ISSUE THREAD

**Issue by seniorivn** [ro31337/libretaxi#440]
hi, is it non profit project?
Why did you create this, on the main page there is nothing about.
situation is almost like with durov's telegram.
Why should i believe it will be free forever? how do you(this project) finance yourself?

**Comment by ro31337** [comment]
There are many projects with open source and no monetization. Ex: libreoffice.org There are ~200M users. They don't need monetization. I was able to build LibreTaxi and I'll be able to support it. There are plenty of companies who can support this mission. I need to investigate it little bit more and apply.

**Comment by seniorivn** [comment]
@ro31337 yeah, i understand, that it's possible to develop this project because you want to, but it's not application that works on user side like libreoffice, it's more like wikipedia, that's need money for the server side infrastructure, and with big audience(like uber's) you will need a lot of money, so if you don't have a plan, it's time to find one, and i personally as a future user would like to hear it.

if it's profit project with opensource code, it's more understandable, but public monetization plan still wanted.

### #offtop
- And personally i don't believe that this centralized alternative for uber like companies will be popular enough to work on real market. Even if you smart/financed/talented/etc enough, i doubt it will be possible(but i hope i'm wrong)

- May be you should consider to find decentralized solution, may be using blockchain. Without need for server infrastructure, and with minimized fee, it could be concurrent enough.

**Comment by ro31337** [comment]
I agree, there are many challenges. If decentralized solution won't hurt user experience, it will be implemented. You have nice theory, but the practice is that nobody will use the app if it's slow. This is what it is now.

I'm planning to work on the app and continue development. I don't think about money, and I don't believe in expensive server infrastructure. As for the server, there are plenty of companies who are willing to give server resources for free.

Also, you're thinking about Uber as perfect piece of technology, and even idealize it. They're extremely inefficient. LibreTaxi will outperform them easily, only by applying right practices (with the help of other developers around the world, of course). However, it's not the goal, and Uber is not our direct competitor.

I would recommend one thinking about LibreTaxi in terms of intellectual supremacy. It's not about money, it is not about service, hosting, etc. If decentralized solution is possible to implement, it will be implemented.

**Comment by seniorivn** [comment]
Thank you and good luck.
