### ISSUE TITLE
interface the bot with Facebook messenger

### ISSUE THREAD

**Issue by ericfont** [ro31337/libretaxi#442]
Since LibreTaxi is really just a bot, I would think it would be straightforward to allow the bot to also interface with Facebook Messenger, which also supports bots: https://developers.facebook.com/blog/post/2016/04/12/bots-for-messenger/

There are many people already on facebook, and there is a tendency of people to be wary of installing extra apps, so could increase userbase by reaching them where they are already hanging out.

**Comment by ro31337** [comment]
merged with https://github.com/ro31337/libretaxi/issues/442

**Comment by jsappme** [comment]
+1

**Comment by ro31337** [comment]
@jsappme I started working on FB interface. ETA is unknown, hopefully soon. Also, I appreciate if you can say few words about why `+1` and why it's important for you.

**Comment by jsappme** [comment]
@ro31337 great news. FB Messenger is a lot more popular than Telegram, a lots of people do not want to install another app to chat (specially with a chatbot).

**Comment by jsappme** [comment]
@ro31337 how can I help in the dev of this new feature?

**Comment by ro31337** [comment]
Implement 8 handlers, similar to these: https://github.com/ro31337/libretaxi/tree/master/src/response-handlers/telegram

Use facebook native API, Broid (mentioned in other story) has bad support of some required features. Don't care about facebook setup code too much - it's _not_ very important at the moment, but anyway, try to keep it nice and shiny. We need handlers first. When they're done, I can jump in into your changes and do the rest.

At the same time I'll work on FB handlers in parallel (however, I have something else to do). So hopefully you'll be able to deliver it first. If not - you'll have a great experience and hopefully fun with Facebook API :)

**Comment by ro31337** [comment]
Also, on your way you can share your code time to time and ping me. I can take a look. I would share my code, but it's not shareable at the moment, too much random stuff. However, I will push my branch with this feature (or even with my minor changes related to this feature) when I can.
