### ISSUE TITLE
Add support for Matrix.org transport

### ISSUE THREAD

**Issue by bigfack** [ro31337/libretaxi#445]
I believe [Matrix](https://matrix.org/) excels at all the factors listed in support of Telegram, with the added benefits of being an open and federated protocol.

Matrix is:
   - Available for all popular platforms
   - Contains rich bot API
   - Fast, reliable, and secure
   - Works perfect with slow/poor Internet connection
   - Free and opensource software
   - Federated

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
