### ISSUE TITLE
Integrate Broid to enable others chat platforms

### ISSUE THREAD

**Issue by jeanbaptistemorin** [ro31337/libretaxi#453]
Using @broidHQ will enable more messaging platforms.
Actually Broid support: Slack, Twitter, Viber, Line, Callr, Twilio, Skype, Discord, Messenger, Telegram, Kik and Flowdock.

This may fix: https://github.com/ro31337/libretaxi/issues/452, https://github.com/ro31337/libretaxi/issues/442 and maybe also https://github.com/ro31337/libretaxi/issues/448, https://github.com/ro31337/libretaxi/issues/445

**Comment by ro31337** [comment]
To someone who want to work on this one:

Investigate if following is possible at least on one of mentioned platforms (except Telegram):

* display a set of buttons
* ask user to provide phone number
* ask user to provide location

If something of mentioned above is not possible, issue can be closed until improvements are made to the platform(s) API.

(TBH I doubt that Messenger, Skype, Twitter are able to display a button or have API to ask a phone number)

**Comment by rocketinventor** [comment]
I know for sure that Skype _does_ support buttons. I also know that you can fetch a user's _real name_ from their API.

The bot could just _ask_ for phone numbers.

**Comment by killix** [comment]
Hi,

I am really happy to hear that you think about use Broid project for this amazing idea.

You can find all the details in each integration readme. 
For example, [skype](https://github.com/broidHQ/integrations/tree/master/integrations/broid-skype) support buttons. Skype doesn't support location and phone number.

Below the recap for each platform.

| Plateform  | buttons  | location  | Phone number |
| ---------- |:--------:|:--------:|:--------:|
| [Slack](https://github.com/broidHQ/integrations/tree/master/integrations/broid-slack)          | x  |   |   |
| [Twitter](https://github.com/broidHQ/integrations/tree/master/integrations/broid-twitter)      |    |   |   |
| [Viber](https://github.com/broidHQ/integrations/tree/master/integrations/broid-viber)          | x  | x |   |
| [Line](https://github.com/broidHQ/integrations/tree/master/integrations/broid-line)            | x  | x |   |
| [Callr](https://github.com/broidHQ/integrations/tree/master/integrations/broid-callr)          |    |   |   |
| [Twilio](https://github.com/broidHQ/integrations/tree/master/integrations/broid-twilio)        |    |   |   |
| [Skype](https://github.com/broidHQ/integrations/tree/master/integrations/broid-skype)          | x  |   |   |
| [Discord](https://github.com/broidHQ/integrations/tree/master/integrations/broid-discord)      |    |   |   |
| [Messenger](https://github.com/broidHQ/integrations/tree/master/integrations/broid-messenger)  | x  |   |   |
| [Kik](https://github.com/broidHQ/integrations/tree/master/integrations/broid-kik)              | x  |   |   |
| [Flowdock](https://github.com/broidHQ/integrations/tree/master/integrations/broid-flowdoc)     |    |   |   |

The coming integrations (plan for this week)

| Plateform  | buttons  | location  | Phone number |
| ---------- |:--------:|:--------:|:--------:|
| [Google Assistant](https://github.com/broidHQ/integrations/tree/master/integrations/broid-google-assistant)          |   |   |  |
| [Gitter](https://github.com/broidHQ/integrations/tree/master/integrations/broid-gitter)      |    |   |  |
| [Nexmo](https://github.com/broidHQ/integrations/tree/master/integrations/broid-nexmo)        |    |   |  |
| [IRC](https://github.com/broidHQ/integrations/tree/master/integrations/broid-irc)            |    |   |  |

**Comment by ro31337** [comment]
@killix what does "x" mean? " ❌ No " ? or " ✅ Yes " ? Is it possible to replace with  ✅  or  ❌  ?

**Comment by killix** [comment]
Just published: Alexa, Google Assistant, Gitter, Nexmo, IRC, GroupMe.

_Note: The PR to add location to Messenger is in Review._

**Comment by jsappme** [comment]
+1

**Comment by rocketinventor** [comment]
How do you use it on Alexa?

**Comment by mikeres0** [comment]
Any update on this integration?

**Comment by ro31337** [comment]
No any details have been posted by people involved in conversation for a long time, closing.
