### ISSUE TITLE
Use Blockchain such as Ethereum instead of Google Firebase

### ISSUE THREAD

**Issue by dctremblay** [ro31337/libretaxi#455]
Hi ! I've just heard about LibreTaxi at local radio station.

I find the principle of that service very cool, that's what everyone needs, it must absolutely be free and open source.

The only thing that frustrate me is that is using a proprietary database service (Firebase). I think that some decentralized database such as some blockchain technology would be the best for that kind of project. Ethereum can help you more easily implements that, or OpenDHT if you want to go more straightforward.

If you agree with that idea and need help about this, I would be absolutely interested to contribute.

Thank you very much and have a great day !

**Comment by iSasFTW** [comment]
+1 For Ethereum.

**Comment by Y75QMO** [comment]
+1 for Ethereum. Ethereum payments get confirmed in 15 seconds and they cost less than $0.01. Bitcoin on the other hand can take hours to get confirmed and it can cost up to $1 in fees.

**Comment by ro31337** [comment]
No ETH or other blockchain until existing problems resolved. Closing till the better time.
