### ISSUE TITLE
Accept Ethereum (ETH-Ether) payments, please.

### ISSUE THREAD

**Issue by Nogreedy** [ro31337/libretaxi#457]

**Comment by Y75QMO** [comment]
Yes, please support Ethereum. The problem with Bitcoin payments is that they can take hours to get confirmed and they can cost up to $1 in transaction fees.

Ethereum on the other hand gets confirmed in 15 seconds and transaction fees cost less than $0.01.

If needed, Ethereum allows for multisig escrows and smart contracts. Please, allow Ethereum.

Ethereum is a joy to use. Thank you for LibreTaxi.

**Comment by ro31337** [comment]
Thanks for sharing your opinion, Ethereum support will be implemented. ETA is unknown, however. Hopefully soon.

**Comment by rocketinventor** [comment]
Ethereum would probably negate the need to build a fancy payments system like the one I described in #458.

**Comment by ro31337** [comment]
No Ethereum until existing problems resolved. Closing till the better time.
