### ISSUE TITLE
Slow connection on some devices

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#462]
Some devices have slow connection, about 5 minutes to reply. Seems it's rare. Steps to reproduce are unclear. Will try to update `tgfancy` package. Also CC @GochoMugo

![image](https://cloud.githubusercontent.com/assets/1477672/22538571/3383472c-e8c8-11e6-9023-5c351baa7326.png)

Other bots (like `@qwasapbot`) work okay.

![image](https://cloud.githubusercontent.com/assets/1477672/22538592/5bd23350-e8c8-11e6-9a05-d9cd58889bd5.png)

**Comment by ro31337** [comment]
Deployed with this update, awaiting for test results.

**Comment by GochoMugo** [comment]
you may need to include more debugging information.

**Comment by ro31337** [comment]
I need, without "may", there is no any debugging info at the moment. Only one report from the user. Trying to get as much info as I can

**Comment by ro31337** [comment]
No info on this bug, closing
