### ISSUE TITLE
NPM test not working 

### ISSUE THREAD

**Issue by nacimux** [ro31337/libretaxi#467]
node version : 6.9.2.
OS : Windows 8.1

When i try to run the  "npm test" command, i have this error : 

`libretaxi@0.1.0 ava C:\Users\Nacim\Documents\projects\libretaxi
> TEST_ENVIRONMENT=true ava --concurrency=5 --require babel-register "./test/before-all.js"

'TEST_ENVIRONMENT' is not recognized as an internal or external command,
operable program or batch file.

`

Same thing for npm telegram, i have this error : 

`
npm ERR! Failed at the libretaxi@0.1.0 telegram script 'babel-node ./src/app-telegram.js'.
`
Can someone help me pls ?

**Comment by maasencioh** [comment]
@nacimux 'TEST_ENVIRONMENT' is an [environment variable](https://en.wikipedia.org/wiki/Environment_variable), therefore you have to use the way that should be to your operative system

**Comment by ro31337** [comment]
Confirming, it's Windows related issue. You should be able to fix it by setting environment variable in Windows.

**Comment by noman115pk** [comment]
@ro31337 I have the same issue. I tried to set TEST_ENVIRONMENT=true as variable and also NODE_ENV=TEST_ENVIRONMENT variable but no luck so far. If i get this to work. I surely will update the Getting Started guide for Windows OS.

**Comment by ro31337** [comment]
@noman115pk this is known issue for Windows. Looking for someone who can fix shell scripts.

**Comment by hirako2000** [comment]
#501

**Comment by ro31337** [comment]
@nacimux please check the latest master and close the issue if everything's fine. It worked for me. If no action taken, issue will be closed in two weeks from now. Thanks everyone for working on this, it was very important.

**Comment by ro31337** [comment]
Closing this issue, problem has been resolved.
