### ISSUE TITLE
website text is not legible

### ISSUE THREAD

**Issue by slowkow** [ro31337/libretaxi#469]
You might consider a different font for your website. Here's how it looks on my screen. I can't read it.

Chrome, Mac OSX

![libretaxi_-_free_and_open_source_uber_lyft_alternative_](https://cloud.githubusercontent.com/assets/209714/22597934/a63c0c9e-e9ff-11e6-96fa-0cffb5982580.png)

**Comment by ro31337** [comment]
Thank you, will check.

**Comment by ro31337** [comment]
recreated here: https://github.com/ro31337/libretaxi-www/issues/20
