### ISSUE TITLE
Add language selection paging

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#479]
Before we can add more languages, we should implement some sort of paging.

Here is how it looks now:

![image](https://cloud.githubusercontent.com/assets/1477672/22623515/6a083bc6-eb12-11e6-917d-af9aa56ce1e5.png)

Telegram has limitation, it can display 6 buttons only.  So instead of displaying Turkish, display button with right arrow:

## Option 1

| | | |
|-|-|-|
| 🇬🇧 English | 🇪🇸 Español
|🇮🇩 Bahasa Indonesia| 🇧🇷 Português
|🇷🇺 Русский| 🇹🇷 🇩🇪 🇫🇷 →

(I didn't want to introduce 🇬🇧 and 🇪🇸 , but seems like for users it will be less confusing)

When user clicks next button (🇹🇷 🇩🇪 🇫🇷 →), it shows the following screen:

| | | |
|-|-|-|
| 🇹🇷 Türkçe |  🇩🇪 Deutsch
| ← 🇬🇧 🇪🇸 🇮🇩 🇧🇷 🇷🇺 | 🇫🇷 Français

## Option 2

| | | |
|-|-|-|
| English | Español
|🇮🇩 Bahasa Indonesia| 🇧🇷 Português
|🇷🇺 Русский| →

or

| | | |
|-|-|-|
| 🇹🇷 Türkçe |  🇩🇪 Deutsch
| ← | 🇫🇷 Français

## Option 3

| | | |
|-|-|-|
| English | Español
|🇮🇩 Bahasa Indonesia| 🇧🇷 Português
|🇷🇺 Русский| ... →

or

| | | |
|-|-|-|
| 🇹🇷 Türkçe |  🇩🇪 Deutsch
| ← ... | 🇫🇷 Français

IMO option 3 looks cleaner and more intuitive.

It's OK for now to add "page2" value for "... →" and "page1" value for "← ...". In other words, there is no mechanism of paging, just something that works with 2 pages only.

**Comment by rocketinventor** [comment]
I like option 1 b/c it is more visually consistent.

**Comment by ro31337** [comment]
@rocketinventor  Unfortunately with 15 or more languages it won't look this efficient.

**Comment by rocketinventor** [comment]
@ro31337 True. Do we really need 3 pages of menus, though?
I don't think there is any need for a back arrow because you can always just type it out.

**Comment by ro31337** [comment]
I don't understand what do you mean, sorry. Can you provide an example, if possible? Thx

**Comment by ro31337** [comment]
Closing the issue, discussion is OK

**Comment by rocketinventor** [comment]
@ro31337 If it is asking for language, I can just type in "English", right?
