### ISSUE TITLE
Share my location does not work on web version with firefox

### ISSUE THREAD

**Issue by pangard** [ro31337/libretaxi#481]
It is not possible to participate in libretaxi if the location is not correct. I'm testing libretaxi at home, one computer is the driver, the other a passenger, and it works fine from the web version, except that firefox does not get our location right. That sure is firefox's problem, but it stops us from using libretaxi. I've read firefox's "share location" feature depends on google location services.

My question is: is it possible to introduce the location in a different way? I know my coordinates, can I paste them in the right format?

**Comment by ro31337** [comment]
Interesting, are you limited to Firefox? What about Chrome?

Or maybe try plugin https://addons.mozilla.org/en-us/firefox/addon/geolocater/ ?

**Comment by pangard** [comment]
El 06/02/17 a las 00:07, Roman Pushkin escribió:
>
> Interesting, are you limited to Firefox? What about Chrome?
>

Chromium produces an error, could not locate. Anyway, I guess it would
depend on Google location services, like firefox does.

> Or maybe try plugin
> https://addons.mozilla.org/en-us/firefox/addon/geolocater/ ?
>

I tried it, it seems like it broke several firefox versions ago.

**Comment by pangard** [comment]
Ok, this is the whole story: the way that firefox uses to find my location is to use google location services: firefox reads the available nearby wifi spots, it sends the distance to each wifi spot and google, using its database of wifi spots, computes my location and returns it.

So, if wifi is disabled, or you use a desktop with no wifi connection, or you are in a really remote area without nearby wifis, or that has never been mapped by the google vehicles, then google location services fails completely.

So both from a practical point of view, and from a privacy point of view, I think it would be very interesting to be able to enter the coordinates by some other method, for example by replying to a query from the bot. That shouldn't be hard, no? What do you think?

**Comment by pangard** [comment]
- If the **geolocator** firefox add would work, that should be enough.
- Otherwise, it would also be interesting (and simple, I think) to be able to _configure libretaxi to always use the same fixed location_.
   * Think of a _physical "libretaxi spot"_, a bar with a _cased smartphone in kiosk mode_ where you can check if there are nearby drivers, and call them, and you wouldn't need a smartphone, nor to install anything to find a ride.
    * I, for example, would like to offer my car _only as car pooling_. If you happen to travel my way, I'll take you for free, but I will not change my schedule to drive you anywhere else. So I'd only turn on libretaxi at one or two locations. I know the coordinates by heart, so I don't need to give google any info about the nearby wifi spots. BTW, It would also be nice to advertise that I'm going through road X, and would deviate a little bit to get and drop passengers.

In any case, thanks a lot for your proposal. It is a breeze of fresh air in this era of [apploitation](https://www.policyalternatives.ca/publications/monitor/apploitation-city-instaserfs).

**Comment by rocketinventor** [comment]
The ability to enter a street address (and get a confirmation + map back) would be great for many and would solve the issues of not all clients supporting geolocation (which is not always accurate).

Established apps like Uber (and Lyft) already have this feature.

**Comment by userj** [comment]
> The ability to enter a street address (and get a confirmation + map back) would be great for many and would solve the issues of not all clients supporting geolocation (which is not always accurate).

> My question is: is it possible to introduce the location in a different way? I know my coordinates, can I paste them in the right format?

This is important. Right now it relies on Google location services. It would be nice to have an open format for geolocation that is independent of that. The code is accepting some kind of format. We just need to know what that is. I have tried many things with no luck. OSMAnd locations are not accepted either. Only Google maps locations appear to be supported, but I don't use want to use that.

**Comment by ro31337** [comment]
Here is example where location is processed for passenger:

https://github.com/ro31337/libretaxi/blob/master/src/actions/menu/passenger/request-location.js#L50

It takes the value from

https://github.com/ro31337/libretaxi/blob/master/src/app-telegram.js#L24 (`getLocation` in the same file)

And it's validating location in https://github.com/ro31337/libretaxi/blob/master/src/conditions/location.js#L35

I can change validation logic, so it will support string also. So you could specify `37.421955, -122.084058` 1) from your client (not implemented) and also 2) send it through the browser (like it is already implemented now). Is it something that everyone would like to have, and is it OK?

**Comment by userj** [comment]
Thanks for the quick response. 

> I can change validation logic, so it will support string also. So you could specify 37.421955, -122.084058 1) from your client (not implemented) and also 2) send it through the browser (like it is already implemented now). Is it something that everyone would like to have, and is it OK?

I think this string idea is nice because it would also work on every version and platform of telegram.

> Or you guys want ability to enter street address (in this case it won't fulfill "it relies on Google location services")?

For me that would depend on a bit more clarification of my initial statement. I am talking now more about android than the initial Firefox discussion. If entering addresses requires Google play services etc on the device itself, then it would leave out those who didn't install such things. If it is grabbing the data from an external Google service then that would be a work around.

**Comment by ro31337** [comment]
OK, I'll make it silently (without user notification). But we should think about informing user about this opportunity, so they can just enter string geo coordinates.

**Comment by ro31337** [comment]
FYI all, this feature was implemented:

![image](https://cloud.githubusercontent.com/assets/1477672/24326832/f87edc88-1174-11e7-8c3f-408eceb43663.png)

**Comment by pangard** [comment]
Tested it with telegram web + firefox, works great.
Thanks!

**Comment by userj** [comment]
Working well for me too. Thank you for this

**Comment by ro31337** [comment]
Also, added map here: https://github.com/ro31337/libretaxi/issues/563

Now when you _type_ coordinates, you'll see the map (see issue above for details and screenshot).

**Comment by ro31337** [comment]
Also:

Now you can just type address instead of coordinates: https://github.com/ro31337/libretaxi/issues/548

No need to share your exact location
