### ISSUE TITLE
Firebase console link 404

### ISSUE THREAD

**Issue by davidlee1435** [ro31337/libretaxi#492]
Tried clicking the link to the Firebase console in the Getting Started page and it took me to [this url](https://github.com/ro31337/libretaxi/blob/master/doc/libretaxi-development-credentials.json) instead of [the URL that I expect](https://console.firebase.google.com/).

PR is up here: https://github.com/ro31337/libretaxi/pull/493

**Comment by ro31337** [comment]
Thanks a lot! Merged
