### ISSUE TITLE
How can I install and configure libretaxi.org?

### ISSUE THREAD

**Issue by LuisBruno** [ro31337/libretaxi#498]
Hello, I just have html, php, css and mysql knowledge but I do not know js node, that's why I would like a more detailed manual on how to install libretaxi.org and configure it and edit it with my preferences, try to install js node, Los Settings, install the bot in the instragram but until there I stay, I hope help, thanks.

**Comment by ro31337** [comment]
@LuisBruno thanks for letting know about it. Let us know what you've done and what kind of issues you had. As much details as possible. Teaching the basics of Node.js is not the mission of this project. If it is something related to LibreTaxi, I'll try to help. I need to make sure you tried everything you can before I can jump in with detailed instructions. Also, specify your O.S. and steps to reproduce errors.

**Comment by mauphung** [comment]
Is-there any description of libretaxi program architecture or data flow available?
Rider request -> ??? -> ??? -> ??? > Driver response -> ??? -> ??? -> ??? >

**Comment by ro31337** [comment]
Here is short description (I'll update docs later):

Raw Request -(goes to)-> Action -(returns)-> Response

Raw request goes to action based on specific user state (`menuLocation`). Action returns subtype of Response (which is usually CompositeResponse that contains multiple responses).

So everything is organized around actions. See `routes.js`. There is a map of user states and corresponding actions.

**Comment by mauphung** [comment]
Thank you very much for your response. Please correct my understanding as belows if I'm wrong:

app-cli.js waiting for request from Passenger/Driver then routes.js to coresponding class
The request sent from iphone or android device and these device received the data from app-cli.js

Passenger/Driver (iphone/android device) → send request → app-cli.js of node.js → routes.js → [telegram + firebase + redis] →response → Passenger/Driver (iphone/android device)

**Comment by ro31337** [comment]
Yes, that is correct. Every user at any moment is located at specific action (or "default" action for new users). So to understand what will be executed, you just need to find this action based on routes and see in its class.

**Comment by mauphung** [comment]
Libretaxi is very good for my learning purpose. I would like to learn libretaxi program from the source, can you write some more guides for developer such as "How code.js communicate with telegram from which class?", "How libretaxi use firebase and redis?", "How to customize libretaxi?", etc...
There is redis for windows platform, can I develop and run libretaxi in windows 10?
Is there any on-line course to learn libretaxi?
Thank you very much in advance.

**Comment by ro31337** [comment]
That would be great posts. One day I'll definitely write about that. But it will take some time, today it's no my priority. There is some very important work that needs to be done, and I'm totally focused on that.

**Comment by ro31337** [comment]
No constructive discussion, closing

**Comment by accttec** [comment]
Hi There, 

is there anyone who can help me to deploy LibreTaxi in my locality 

Thanks

**Comment by MFaheemRajput** [comment]
you have to deploy the whole system by own.

**Comment by alemat** [comment]
any manual how to create the bot and manage drivers, passengers ?
