### ISSUE TITLE
How do I get the menu on my bot?

### ISSUE THREAD

**Issue by easyguyme** [ro31337/libretaxi#502]
I have followed all the instructions and installed libre taxi successfully, the problem is am not getting the menus when using the bot, am only getting the /start button then  nothing else.

**Comment by ro31337** [comment]
Please post a screenshot. THanks

**Comment by easyguyme** [comment]
![desktop](https://cloud.githubusercontent.com/assets/9677504/22874619/22d2dfbe-f1d8-11e6-90fe-0d6bcc10c015.PNG)
![server](https://cloud.githubusercontent.com/assets/9677504/22874628/2d2cb7dc-f1d8-11e6-8930-ef881c60beb6.PNG)

Please find above my screenshot

**Comment by ro31337** [comment]
What do you have in logs?

**Comment by easyguyme** [comment]
After running `npm run telegram` am still getting the same results.
Below are my logs

```
[2017-02-14 06:51:43] [debug] Init complete, default language set to en
[2017-02-14 06:54:24] [debug] Init complete, default language set to en
```

**Comment by ro31337** [comment]
Create public or private repo with your credentials and give me access please.

**Comment by easyguyme** [comment]
Please check your mail. I have shared from my  cloud 9 workspace. Thanks

**Comment by ro31337** [comment]
For reference: issue was fixed. There was confusion in one step from Getting Started, probably needs to be improved. @easyguyme I appreciate if you can add what you think is important and create PR. Thx!

**Comment by skycold** [comment]
Hi guys, I'm installing the environment and I'm facing the same issue.
Could you tell me how you resolve it ?  @ro31337 @easyguyme 
thanks in advance

**Comment by easyguyme** [comment]
@skycold please check your firebase connection url is exactly the way it appears on firebase

**Comment by ro31337** [comment]
No information provided, assuming issue was resolved for everyone. Also provided help to others and got no promised documentation fix. Thanks for supporting open source.
