### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#507]
Travis CI just needs to be added, so we can have automatic checks on every commit/PR.

It just should have node from `.node_version` and should run `npm test`. Note that some checks may fail in `before-all.js` (read LibreTaxi docs about that please). Let me know if this is the issue.

**Comment by morrme** [comment]
Does this require collaborator-level access to complete?

**Comment by ro31337** [comment]
If you need any access, let me know. I don't remember how exactly collaboration/integration works in TravisCI. If you need GitHub permissions to complete this story, just let me know.

**Comment by morrme** [comment]
I just tried and it says 

`You require admin rights to enable these repositories`

I can only enable it for a fork I make, not the primary one.

**Comment by ro31337** [comment]
Thanks for trying. I invited you to repo collaborators

**Comment by ro31337** [comment]
You should be good to go now. Feel free to create PR and test in the `master` branch if it's required. Please do not use force push and do not switch off master branch protection. If you'll ever need to revert commit for some reason you can do `git revert`. Don't rebase, use merge.

Basically - it's okay to pollute master branch a little bit, okay to create new branch and/or some PRs, but don't overwrite history :)

**Comment by morrme** [comment]
Here's what I've learned:

As a collaborator I should be able to do configuration but I cannot "flip the switch" initially. Only those with admin access can do that [(reference)](https://docs.travis-ci.com/user/getting-started/). As the repo owner, you must first visit https://travis-ci.org/, sign in with GitHub, then turn Travis on for this repo. 

Then I'm happy to help with everything else :smile:

**Comment by ro31337** [comment]
Thanks, should be done now:

![image](https://cloud.githubusercontent.com/assets/1477672/25211193/d6742454-2538-11e7-95dc-575a6f0702e4.png)

**Comment by morrme** [comment]
It is, and I've confirmed I can now configure from my end:
![libretaxi](https://cloud.githubusercontent.com/assets/26514778/25211323/5c941560-254a-11e7-98c6-eb72dd62d81c.GIF)

**Comment by ro31337** [comment]
Hi @morrme, looks good. You should create `settings.js` - see here https://github.com/ro31337/libretaxi/blob/master/doc/GETTING-STARTED.md

**Comment by ro31337** [comment]
Hey @morrme do you have any updates on Travis? Or I can take a look at that! Thanks!

**Comment by ro31337** [comment]
Cheers to everyone who was working on this!
