### ISSUE TITLE
Two Way Rating system for the service

### ISSUE THREAD

**Issue by joicemjoseph** [ro31337/libretaxi#513]
it seems there is a chance of problems when an autonomous person starts providing rides.

such person starts molesting or stealing will result in the systems' credibility. So, as a solution, I suggest to incorporate two way ride rating system. 
Lets say out of five. and that will possibly avoid such possibilities.

**Comment by rocketinventor** [comment]
I think think this issue has already been discussed in #404. Feel free to join the discussion there.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
