### ISSUE TITLE
Integration with bitrated.com

### ISSUE THREAD

**Issue by HostFat** [ro31337/libretaxi#523]
Maybe this can be useful to get an early score on the reputation.

**Comment by rocketinventor** [comment]
I wouldn't use it for reputation but, its anti-fraud tools such as ```multi-signature reversible payments``` may be useful once the API is released.

**Comment by shesek** [comment]
Hi, Nadav from Bitraded here. The APIs for integration are not quite ready yet, but we're working on it and will hopefully have some news to share soon. We'll probably start by releasing the identity and reputation related APIs first, followed by the payment related APIs later.

I understand that the reputation APIs are less relevant for LibreTaxi (happy to hear why if you want to share), but I'll keep this issue updated regarding the payment API when we start rolling it out.

Cheers and good luck.

**Comment by ro31337** [comment]
No integrations with proprietary services. Closing.
