### ISSUE TITLE
Wrong _desc string in en.json

### ISSUE THREAD

**Issue by thenhustey** [ro31337/libretaxi#524]
en.json ([line 111](https://github.com/ro31337/libretaxi/blob/master/locales/en.json#L111)) Wrong description string.
`"passenger-verify-cash.get_some_cash_desc": "Here we ask users to try the different way of sending location. Instead of clicking the button, they can try to use Telegram menu.",`

**Comment by ro31337** [comment]
Thanks for reporting this bug, fixed!
