### ISSUE TITLE
Feature request: add number of demanded/availible seats in a car

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#533]
From our [Telegram chat](https://t.me/libretaxi):

Add number of demanded/availible seats in a car. (Or add demand for this information to order/check-in desctiption)

**Comment by jiriha51** [comment]
Hi Roman, I'm looking for someone to collaborate on libretaxi here in the Czech Republic, do you know anyone?

**Comment by ro31337** [comment]
Hi, @thenhustey has contributed Czech translation. There is one guy in our Telegram group: https://t.me/libretaxi (may be more, not sure though).

And there is an article about that http://connect.zive.cz/bleskovky/libretaxi-open-source-alternativa-pro-sdilenou-jizdu-kazdy-si-muze-zalozit-vlastni-uber/sc-321-a-186329/default.aspx

This is all I know :)

**Comment by jiriha51** [comment]
thx :)

  ----- Original Message -----

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
