### ISSUE TITLE
Can't change user from "driver

### ISSUE THREAD

**Issue by honeypy** [ro31337/libretaxi#535]
Occasionally i haver i registered like a driver, but now i want to be a passenger. I have cleared history, deleted chat, restarted bot, but it sending message that he doesn't understand my address and asking to send location again. Driver's mode is working okay (but i didn't get requests from passengers).

**Comment by ro31337** [comment]
Please post your screenshot(s).

**Comment by honeypy** [comment]
![bug](https://cloud.githubusercontent.com/assets/14203269/23568414/d1a6e95a-0073-11e7-9a9c-9317813a68a2.png)

**Comment by ro31337** [comment]
This screenshot looks cut. There should be keyboard below, or input field. If it's input field - there is small icon (looks like 4 squares). Click to display keyboard. Then click on the button on this keyboard and go ahead until you see "Settings".

It it doesn't work, please post full screenshot.

**Comment by honeypy** [comment]
![photo_2017-03-15_12-38-05](https://cloud.githubusercontent.com/assets/14203269/23942116/4a512026-097c-11e7-984d-57e8c1688af1.jpg)
![photo_2017-03-15_12-38-17](https://cloud.githubusercontent.com/assets/14203269/23942115/4a50759a-097c-11e7-8b82-6672c7d08519.jpg)

**Comment by honeypy** [comment]
![photo_2017-03-15_12-38-05_150x267](https://cloud.githubusercontent.com/assets/14203269/23942216/97290c6a-097c-11e7-9d48-6c824df273ca.jpg)
![photo_2017-03-15_12-38-17_150x267](https://cloud.githubusercontent.com/assets/14203269/23942217/97296f84-097c-11e7-9c32-87e49bb7badb.jpg)

**Comment by ro31337** [comment]
Hi, please click on the icon before paperclip (looks like four squares). Send location, and move to the next steps until you see "Settings" icon. This bug/confusion is well known and we have  a story for that. But now you can workaround this by just following suggested steps.
