### ISSUE TITLE
Add a button to switch between passenger and driver

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#552]
Add a button to main menu so I can switch easily between passenger and driver. Do not show this button if I wasn't a driver before (we can check last checkin date).

Here is how button text may look like:

* `⇄`
*  `⇄ Passenger` (in driver menu)
* `⇄ Driver` (in passenger menu)

Button should be displayed at the bottom row on the right. So bottom row will have two columns.

**Comment by ro31337** [comment]
Looks confusing now:

![image](https://cloud.githubusercontent.com/assets/1477672/25307993/116134b6-2760-11e7-8695-167c84753820.png)

Not sure if it's required. Interface should be simple, no ugly buttons. Will think about implementation.

**Comment by morrme** [comment]
maybe have the button above and not below the prompt? 

or maybe at least in its own row?

**Comment by ro31337** [comment]
There is limitation in Telegram - 3 rows and 3 columns (9 buttons max). It's not bad IMO, it's even good - don't confuse users they say. May be I should move it to settings. You click settings and you're in settings menu where there are three options:

* 🔧 Start over (or reset settings)
* ⇄ Driver
* ↩️ Back

**Comment by morrme** [comment]
yeah, moving to settings makes sense because switching between roles doesn't seem like something that will need to be done frequently anyway. 

from a UX perspective, the current position of that button could be hit by mistake often.

**Comment by ro31337** [comment]
Let's add no buttons. Just add slash command: `/flip`. I think it's enough.

**Comment by ro31337** [comment]
No help for a long time here, closing.
