### ISSUE TITLE
npm ERR! Tell the author that this fails on your system: npm ERR!     eslint src test

### ISSUE THREAD

**Issue by jessecotto** [ro31337/libretaxi#554]
Just following instructions.

I followed every step of the Getting Started guide with no results. I played with it for more than 6 hours today with no results. 9300 problems.

If I `npm run telegram` I get these: 

Tell the author that this fails on your system:
npm ERR!     babel-node ./src/app-telegram.js

I'm not sure what I might be doing wrong; but there is really not much info around for babel (I guess is too confusing) that will help me clarify this.

Please let me know how I can overcome this issue as I haven't dedicated much time to coding for quite some time and is a little frustrating to find this issue on my second day after a comeback.

Please advice.

**Comment by ro31337** [comment]
Sorry about your time waste. What OS do you have? Also, npm and node versions?

Screenshot will be also helpful.

Thanks!

**Comment by jessecotto** [comment]
Hi Roman,

Thanks for your Super fast reply! No problem, I think we can make it work
with your help!

I've attached some screenshots with the details. The two terminal
screenshots were too long so I got the end only.

Screenshots:

1 - OS
2 - Ran npm test
3 - Ran npm run telegram

For node I'm using v7.9.0 and 4.2.0 for npm.

Thanks Again.

**Comment by ro31337** [comment]
Hey, I don't see any screenshots.

What about tests? Was `npm test` command okay? Did you do `npm install` before everything?

Node and npm versions should be OK.

**Comment by jessecotto** [comment]
​
Sorry, I place the pics inline now.

npm test gave me those the errors showing in the 1st pic. Yes, I did npm
install before.

Do I need to add the Firebase SDK script anywhere?

Also I tried running aslant and tried every setting Google, AirBnB, etc but
didn't work.

**Comment by jessecotto** [comment]
eslint meant to say

**Comment by ro31337** [comment]
Still don't see any screenshots

**Comment by jessecotto** [comment]
Oh. I wonder why..I can see them on my sent emails folder. -that is weird.

**Comment by ro31337** [comment]
Can you post them directly to GitHub?

**Comment by jessecotto** [comment]
That's is actually why. -I was replying from gmail.

![screen shot 2017-04-15 at 9 53 37 am](https://cloud.githubusercontent.com/assets/7409567/25065606/c60ae0e0-21e0-11e7-9e6f-56b0b0cb1828.png)
![screen shot 2017-04-15 at 9 56 33 am](https://cloud.githubusercontent.com/assets/7409567/25065607/c6140ba2-21e0-11e7-8621-d60f32993d3f.png)
![screen shot 2017-04-15 at 9 58 48 am](https://cloud.githubusercontent.com/assets/7409567/25065608/c6189cda-21e0-11e7-8e88-626ba6d480a1.png)

**Comment by ro31337** [comment]
What's your output if `git rev-parse HEAD` and `git status` commands?

Also, can you try the following:

`rm -rf ./node_modules && npm install` in project directory? And then once again `npm test`.

**Comment by jessecotto** [comment]
I got:

fatal: Not a git repository (or any of the parent directories): .git

on both HEAD and status

I did the rm rf command with install and npm test again; but got same fail:

eslint src test

**Comment by ro31337** [comment]
Let me know if you have your problem fixed. Seems like something is on your system. I wanted to make sure you have the latest and unmodified version, but I can't say that. Seems like you have broken version.

What you need - is to start using git. Something happened to your files while you were downloading source code.

**Comment by ro31337** [comment]
Closing, no follow-up for more than 2 weeks.
