### ISSUE TITLE
Let Uber/Lyft drivers verify themselves

### ISSUE THREAD

**Issue by aadjfpeo** [ro31337/libretaxi#556]
Many drivers work multiple apps. Knowing if a Libretaxi driver was also employed by another company would increase trust and benefit both riders and drivers since those companies do background checks unlike libretaxi.

An uber/lyft badge would serve as a unit of reputation/certification for riders who value it.

Libretaxi only drivers would not be disadvantaged because they would offer the privacy of not having riders locations tracked by a third party.

Hopefully this would only be necessary until an independent rating system is made.

**Comment by ro31337** [comment]
What would be the verification mechanism?

**Comment by rocketinventor** [comment]
I think we should just take a note from Uber's (and allegedly Lyft's) playbook and run an undercover op to _steal_ the data from their servers and use it without permission.

Anyone else on board?

**Comment by ro31337** [comment]
I'm adding `*sarcasm*` to ^^^ so nobody will get confused ;)

**Comment by kamikazechaser** [comment]
Uber restricts their driver endpoints to certain apps which pass their certifications. Lyft doesn't have an endpoint to get driver information. This is a good feature which will add trust to the platform, but there is no way of automatic verification. best bet is to use screenshots from the respective apps.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
