### ISSUE TITLE
Remove Firebase dependency

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#566]
API for mobile apps is coming. LibreTaxi for Telegram should use API only. It should not have any dependencies.

Depends on: API implementation

**Comment by morrme** [comment]
wow!

**Comment by vitalyliber** [comment]
FYI https://medium.com/@contact_16315/firebase-costs-increased-by-7-000-81dc0a27271d

**Comment by iSasFTW** [comment]
Will this be a centralized API?

**Comment by iSasFTW** [comment]
Ethereum could be used for this. No centralized entity controls the system and it essentially stays up forever.
