### ISSUE TITLE
No hosts file or folder

### ISSUE THREAD

**Issue by naumanahmad17** [ro31337/libretaxi#576]
## Step 5. Add changes to your `hosts` file.

(required for development, optional for production).

as i am developing i did'nt find any hosts file 
or this path '/etc/hosts'

as i have recently started working on this.
please guide me  if i may have missed any thing ??

Regards

**Comment by ro31337** [comment]
Your Operating System? Any screenshots?

**Comment by naumanahmad17** [comment]
thanks i get it working :) 
i am closing the issue.
and i  am using Ubuntu :)
