### ISSUE TITLE
run bot in local environment ?

### ISSUE THREAD

**Issue by naumanahmad17** [ro31337/libretaxi#578]
how can i run the bot in local environment. i have setup redis and every thing when i 
i run command `npm run telegram`
i am also attaching a file.
![selection_011](https://user-images.githubusercontent.com/16565514/27793453-8992f36c-6017-11e7-96d2-b2d6ac762006.png)

**Comment by naumanahmad17** [comment]
@ro31337 can you please help

**Comment by naumanahmad17** [comment]
@ro31337 can you please help??

**Comment by ro31337** [comment]
This console message is okay for now (to be fixed in the future). It should work. If it doesn't - provide more screenshots, steps to reproduce, etc.

**Comment by ro31337** [comment]
Assuming issue was resolved, no response for a long time. closing
