### ISSUE TITLE
Urdu Translation Missing

### ISSUE THREAD

**Issue by pakistanimoon** [ro31337/libretaxi#590]
There is no translation provided in urdu for both website and apps.
As this language is being spoken widely in sub-continent it can be a good plus.

**Comment by pakistanimoon** [comment]
libretaxi/ur.json file created for this purpose

**Comment by pakistanimoon** [comment]
[https://github.com/pakistanimoon/libretaxi/blob/master/locales/ur.json](url)

**Comment by MFaheemRajput** [comment]
Hello friends how can i help you in this project.

**Comment by ro31337** [comment]
Hi, everyone! Thanks for translating. Unfortunately not all of the keys have been translated. In most of them translation is missing. There is no need to translate keys ending with _desc (you can remove or just ignore them). But keys without _desc suffix must be translated.

Is there any chance you can finish translation please? @pakistanimoon or @MFaheemRajput 

Thank you!

**Comment by pakistanimoon** [comment]
I can finish it, but problem i was facing is about commiting the code.

**Comment by ro31337** [comment]
No translation, no need to keep the issue open. Closing.
