### ISSUE TITLE
No real need to check-in every hour, update rus/eng translations

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#602]
We're currently asking drivers to check-in every hour. It's not required. I thought it would be good alternative to live coordinates tracking, but it turned out that nobody checking in every hour, and service works fine.

In this story:

* Update rus/eng/ukrainian translations (languages I understand)
* File another story for other translations

**Comment by ro31337** [comment]
This change affects 4 locale keys:

* `driver-explain-checkins.text`
* `driver-explain-whats-next.text`
* `driver-unmute.unmute_ok`
* `driver-checkin.ok`

**Comment by paradox70** [comment]
Ok I'll do it.
