### ISSUE TITLE
Why phone number?

### ISSUE THREAD

**Issue by eemantsal** [ro31337/libretaxi#614]
Why do you need users' phone numbers? You say you won't share my info, then, what do you want it for; do you plan to sell it in a future? Do you store it anywhere? If so, how can users' ask for removal? Also, if I stop the bot will my data be removed from your databases?

Great bot, Libretaxi, but I'm afraid I won't use it until Ican complete the configuration process without providing my phone number.

Regards

**Comment by ro31337** [comment]
Duplicate: https://github.com/ro31337/libretaxi/issues/549

Your phone number is stored in the database. You can type any phone number. If you stop the bot - bot will not get notification about that (platform limitation). Users can ask for removal by emailing me - or you can wait/sponsor for feature(s) you need to be released, this project is open source, and like any other project, without any obligations.

Regards
