### ISSUE TITLE
Telegram Token Error

### ISSUE THREAD

**Issue by smartshare-apps** [ro31337/libretaxi#619]
I am trying to run a local instance of Libretaxi, but I am encountering an error with my telegram token:

`Error: EFATAL: Telegram Bot Token not provided!
`
I've added the token key to my settings.js, and all the NPM tests were passed successfully.
![screen shot 2017-08-23 at 3 56 46 pm](https://user-images.githubusercontent.com/25986518/29635802-2560d594-881c-11e7-85be-435a2b264bc5.png)

**Comment by ro31337** [comment]
Do `ls -lah` in your libretaxi directory and paste output here.

**Comment by smartshare-apps** [comment]
![screen shot 2017-08-23 at 4 18 55 pm](https://user-images.githubusercontent.com/25986518/29636534-f911202c-881e-11e7-8f46-ac6e789cb107.png)

**Comment by ro31337** [comment]
You said:

> I've added the token key to my settings.js

It doesn't look like you have anything in `settings.js`. It's 996 bytes, the same as empty `setting-sample.js` here: https://github.com/ro31337/libretaxi/blob/master/settings-sample.js

**Comment by smartshare-apps** [comment]
Ok - I've changed it, but it still doesn't work. And even with the settings inputted, the file is only 996 bytes. 

Can I just rename setting-sample.js to settings.js? Do I need both files? 

Here's my settings.js attached: 

![screen shot 2017-08-23 at 4 33 56 pm](https://user-images.githubusercontent.com/25986518/29637269-96c8e762-8821-11e7-9599-01d25d90026e.png)

**Comment by ro31337** [comment]
(It's not a good idea to attach settings with credentials, you better change them now, at least remove).

paste the output of your `ls -lah`. Also, which command do you use to run the app?

**Comment by ro31337** [comment]
you need only `settings.js` (sample is not required)

**Comment by smartshare-apps** [comment]
I'm just following these instructions. Everything is fine until I run `npm run telegram`

npm test - Run tests. All tests should pass.
npm run telegram - Start Telegram bot.
npm run build-production && npm run telegram-production - Start Telegram bot for production.
npm run cli - Start CLI version of the bot.
npm run tools:purge - Purge stale orders, see #528

**Comment by smartshare-apps** [comment]
![screen shot 2017-08-23 at 4 50 22 pm](https://user-images.githubusercontent.com/25986518/29637794-3e960942-8823-11e7-90f7-30f3f9653a64.png)

**Comment by ro31337** [comment]
Your settings.js have not been changed, it's still 996 bytes.

**Comment by smartshare-apps** [comment]
Fixed. For some reason it didn't save until I added and removed some text.

**Comment by ro31337** [comment]
Wait a second, what lesson did you learn today? Are LibreTaxi instructions written the right way? Is there anything that can be improved, something that could help you or prevent you from having this issue?

**Comment by smartshare-apps** [comment]
Yes - I will submit some changes to the instructions once I finish the install

**Comment by smartshare-apps** [comment]
Thanks Roman for your attention

**Comment by ro31337** [comment]
> Yes - I will submit some changes to the instructions once I finish the install

I hope so :)

**Comment by smartshare-apps** [comment]
Ok - please review my pull request. 

The next item on my agenda is creating a systems diagram - I think this would be very helpful in order to understand the project structure.

**Comment by ro31337** [comment]
Reviewed, left a comment, thanks! System diagram will be really helpful!
