### ISSUE TITLE
Slow/Partial Responses

### ISSUE THREAD

**Issue by smartshare-apps** [ro31337/libretaxi#621]
Finally got the bot set up, but I am not getting full response functionality yet. 
![screen shot 2017-08-23 at 7 31 59 pm](https://user-images.githubusercontent.com/25986518/29642977-e8e2f99e-8839-11e7-8934-ad84db3da7e8.png)

**Comment by ro31337** [comment]
Please provide the full console log, database dump, steps you already tried to resolve the issue (like clear the database and trying again).

**Comment by ro31337** [comment]
Also, I have some questions for you here https://github.com/ro31337/libretaxi/issues/619, let's close this issue for now and wait for your answers in another story to prevent multiple opening multiple issues from the same author. Don't get me wrong, I want to be sure you're ready to help community back before I can spend more time on fixing your setup.

**Comment by smartshare-apps** [comment]
I'm getting this error. It could be causing the problem. 

`(node:97522) Warning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit`

Just want to see if you've encountered this before, if not I'll manually update the listener limit modules in node.

**Comment by ro31337** [comment]
Never. Can you reproduce this error? Is your problem solved now?

**Comment by ro31337** [comment]
Warning about memory leak is okay for now

**Comment by smartshare-apps** [comment]
Which version of node and npm are you running?

**Comment by smartshare-apps** [comment]
This is only a minor issue, but `npm test` will fail if API keys included in `settings-sample.js`. As a PR, instead of `cp settings-sample.js settings.js` would it be possible to `mv settings-sample.js settings.js` so it is just renamed instead of there being two files?

**Comment by akasha3001** [comment]
i am getting same promblem on ec2 instance.
Bot only respond with ok

**Comment by smartshare-apps** [comment]
Make sure Redis is running on your instance

**Comment by akasha3001** [comment]
yes redis is already working still getting same error

**Comment by ro31337** [comment]
@akasha3001 please post screenshots and full logs. Thanks

**Comment by akasha3001** [comment]
Solved by flushing redis-cli
following steps:
redis-cli
then flushed all keys in the queue using "flushall"
then restart redis server using "service redis-server restart"
and then start libretaxi using "npm run telegram >> telegram.log &"
the last ampersand ensure the command runs in background and is not killed when we kill terminal

**Comment by ro31337** [comment]
I'm using zsh, and my command would be `npm run telegram >> telegram.log &!`

`!` disowns a process, so when you log out, it's still running. There should be also `disown` shell command like: `disown npm run telegram >> telegram.log`

**Comment by ro31337** [comment]
@akasha3001 can you also update readme file (find the right place to do it), and add Troubleshooting section. Please explain there problem you had and how to flush redis (with details if possible). It will help others. Create PR. Thank you!

**Comment by superhimanshu22** [comment]
@ro31337 
I am getting memory leakage issue.

**Comment by ro31337** [comment]
@superhimanshu22 I believe it should be app-telegram.js

I can also see this message, but don't know what it is. Would really like to know where is the issue. If you'll have any info, please let me know.
