### ISSUE TITLE
Use https://le.taxi/ as a Backend for France rides

### ISSUE THREAD

**Issue by oncletom** [ro31337/libretaxi#622]
Hi there,

there is a national platform to book and to locate a taxi in France.
Maybe you want to have a look to plug your product on top of an existing platform :-)

> https://le.taxi/

👋

**Comment by ro31337** [comment]
Can you clarify please and add details? Why do you think it's important and what do you mean by saying "as a Backend"?

**Comment by oncletom** [comment]
Yes sorry.

LeTaxi is a government-backed platform where taxi companies register the position of their fleet, and on which consumer companies build services and products to match users and taxis to generate rides.

As I understand, LibreTaxi does part of this job (acquiring taxi positions and routing consumer requests) — although I guess it means you have to do quite a lot of marketing to plug taxis and people onto the app.

For France, you would have only to build the consumer facing app and tapping into le.taxi API to get available taxis. I don't know if that makes it clearer.

**Comment by ro31337** [comment]
That sounds interesting. We're adding location-specific features at the moment as experiment (https://github.com/ro31337/libretaxi/issues/600), I'll take a look at possible integration scenarios when it's done. Thanks for letting know about this!

**Comment by ro31337** [comment]
No integrations until all problems resolved. Closing
