### ISSUE TITLE
[Feature Request] Offline mobile maps & navigation

### ISSUE THREAD

**Issue by kirantpatil** [ro31337/libretaxi#635]
How about integrating with [OsmAnd](http://osmand.net/) to get offline map and driving directions for below use cases.

1. From Driver location to Passenger location

2. From Passenger location to Destination

**Comment by kirantpatil** [comment]
Here is github issue link that it is integrated with telegram.

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/27

Can somebody confirm it ?

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
