### ISSUE TITLE
node server is crashing

### ISSUE THREAD

**Issue by kirantpatil** [ro31337/libretaxi#637]
Hi,

For testing I have installed libretaxi.

I am using below command to run the app

` $ nohup npm run telegram &`

After doing few operations with driver and passenger, node server crashes.

Thanks.

**Comment by ro31337** [comment]
1. Start without `nohup` command, just follow the guide. Also, no `&` at the end.
2. Provide full crash log
3. Provide screenshots of users interaction

Without this information I won't be able to help.

**Comment by ro31337** [comment]
No response for too long, closing.
