### ISSUE TITLE
[feature request] Adding date of traveling

### ISSUE THREAD

**Issue by frederiiiic** [ro31337/libretaxi#640]
Hi there all,

I'm a new user from france, but right now every times i used the bot i don't get any of them at time.

So i'm thinking of having the possibility to add a date and time of a travel, in this cases we can avoid real time problem of less users in the application. I think this i a good point against new users leaving fast because of less users causing low time answering.

At this time i'm not that good at programming to solve it myself.

Thanks you.

**Comment by ro31337** [comment]
Agree, that would be a very nice feature. I'll think about better implementation.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
