### ISSUE TITLE
Translating to Arabic json does not work for me

### ISSUE THREAD

**Issue by ahmyajk** [ro31337/libretaxi#642]
I translated en.json to Arabic and gave it ar.json then I put it in locales folder in Libretaxi on my server.
also as seen in attached files I updated all the files need to be change due to the new local.
The problem when I run  $npm test    I got 3 exceptions as you can see in attachments. It complain about Arabic character م  in somewhere position. More, when I try out the new language from telegram, it just ignore it and keep showing me menu in English :(. the ar.json attached as well but I convert it to .txt file coz github does not accept json files.
Any help to get arabic language be supported and expand the community.

.
[ar.txt](https://github.com/ro31337/libretaxi/files/1385858/ar.txt)

![10011](https://user-images.githubusercontent.com/4397973/31589236-f9471ad0-b206-11e7-91be-2eded4db34fb.PNG)
![111111](https://user-images.githubusercontent.com/4397973/31589237-f96f232c-b206-11e7-9d75-51738269285c.PNG)
![2222](https://user-images.githubusercontent.com/4397973/31589238-f99928e8-b206-11e7-8bd7-b1c76e75bd5b.PNG)

**Comment by ro31337** [comment]
Invalid escape symbol at key `passenger-index.motorbike` and `driver-select-vehicle-type.motorbike`. Try replacing `\` with `\\` or with `/`.

**Comment by ahmyajk** [comment]
Thats works for me thanks a lot. I will work on official Arabic language so every Arab will understand it and I would like to contribute it here to all.
