### ISSUE TITLE
How can I make price set by passenger accept string not only numeric?

### ISSUE THREAD

**Issue by ahmyajk** [ro31337/libretaxi#645]
I wanna give a chance to the passenger to write the price as a string in addition to numeric? what is the file I should play with to do so?

**Comment by ro31337** [comment]
What have you tried already and what progress do you have?

**Comment by ahmyajk** [comment]
I couldn't find the file that I can change the value to string.

**Comment by ro31337** [comment]
`./src/actions/menu/passenger/request-price.js` - line 56 if I'm not mistaken. There is condition that should be met. I think you can just get rid of `IfResponse`.

**Comment by ro31337** [comment]
No response for a long time, assuming issue is fixed.
