### ISSUE TITLE
What is the support groups and news of Libretaxi on the telegram?

### ISSUE THREAD

**Issue by ahmyajk** [ro31337/libretaxi#647]
What is the support groups and news of Libretaxi on the telegram?

**Comment by ro31337** [comment]
Can you please clarify your question? Thanks

**Comment by ahmyajk** [comment]
I want to join support group and news channel of Libretaxi.

**Comment by ro31337** [comment]
just follow links on libretaxi.org

**Comment by ro31337** [comment]
in the footer

**Comment by ro31337** [comment]
Closing the story: no any ongoing discussion here. Feel free to ping me if this story needs to be reopened. Thank you.
