### ISSUE TITLE
Support share my live location instead of sharing my location every time I moved.

### ISSUE THREAD

**Issue by ahmyajk** [ro31337/libretaxi#648]
We know all recently telegram start supporting sharing live location of user and we know that Libretaxi still need my location every time I change my place. 
I see Libertaxi did not update the code for this new feature. If that feature already added to Libertaxi, how can I update this to Libertaxi on my private server? where is the location files that we have to edit?

![1065011](https://user-images.githubusercontent.com/4397973/32242140-1347792e-be83-11e7-8186-5c9fb962843f.PNG)

**Comment by ro31337** [comment]
That's right, live location would be nice to have. I'm busy with other LibreTaxi related tasks at the moment (which are more important IMO), but anyway:

* You need to add one more request (RequestLiveLocation vs RequestLocation)
* You need to add one more handler
* In particular action - use request you created

I also recommend trying out new solution without LibreTaxi, just plain node + telegram api library. Also you can play with existing one - RequestLocation

**Comment by ro31337** [comment]
If you have any difficulties, post progress you have so far, logs, what you've done, what doesn't work, what you've tried.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
