### ISSUE TITLE
Skip select locale menu

### ISSUE THREAD

**Issue by ahmyajk** [ro31337/libretaxi#655]
I am trying to reduce the steps of libretaxi as much as possible. I removed more than two steps and want to make more simple. 
I got feedback says since we living in the same city and mostly speak same slank language we pushing foreign local too user to pick in the main menu!. Sound logical, so I am looking for the js file that helps me to send user directly to "select-user-type.who_you_are"

**Comment by ro31337** [comment]
Few months ago Telegram api has changed. If I'm not mistaken, now it's possible to get user's language. Not sure how it works, reliable or not. Would appreciate if you dig it up and post results of your research here.

**Comment by ahmyajk** [comment]
I got it, I just changed **default** in .add(new UserStateResponse({ menuLocation: 'default' }));  to select-user-type and it takes me too my local directly.

**Comment by ro31337** [comment]
I'm happy it worked for you. If you think you don't need this issue, feel free to close it.
