### ISSUE TITLE
To build trust, and safety, can we add linkedin profiles to find people from same company

### ISSUE THREAD

**Issue by nikhilrai1984** [ro31337/libretaxi#656]
The thing that is lacking in Libretaxi is trust, especially to be globally adopted, can we bring in some trust parameters into the app,
1) Find a way to segregate people from a same company , by importing linkedin/ facebook profiles for eg:
2) enabling commercial businesses to form groups based on a particular company or community
(apparently telegram can have 30000 people in one group which is amazing)
3) way to charge some way of commercializing or sustenance for persons bringing this service to a community / company
Not sure if all this can be implemented. Or can I use the source code to add these functionalities. Would i need to license or do anything extra if i were to commercialise this for a service that I provide to enterprises?

**Comment by ro31337** [comment]
It sounds interesting. Can you provide some examples for 1 and 2?

3. https://github.com/ro31337/libretaxi/blob/master/LICENSE - we use AGPLv3 license. Anyone can use the source code under this license, run as many instances as they want, modify the source code for free of charge. You should keep the source code and modifications available to everyone.

**Comment by nikhilrai1984** [comment]
Hi Roman,
Thanks for your quick reply, appreciate it.

1) 
I don't have any specific example codes but Lyft 's original idea (zimride) that started with community ridesharing, and was sold to Enterprise.
This is quite impressive with 350K users but has never caught on for some reason .However there is potential to it. Zimride eventually spun a newer product that is Lyft now.

2) Scoop is trying to do this ridesharing within communities and corporates

There are other examples but none of them have a ready reach of worldwide immediate usage such as Libretaxi, Telegram I believe.

3) Not sure why but importing LinkedIn/facebook profiles or going the B2B enterprise way is probably the best way to connect riders from companies or communities.

The model cannot probably self sustain unless there is a way to sustain the workforce/teams that can facilitate it.
Hence, the question about commericalizing came up.

Also, in regards to your No 3 master license, if this were to be implemented, will it eventually form the final current version of Libretaxi or would it be a feature to turn on. More like a generic Enterprise/community feature in the bot itself will be great to have and hence the trust aspect can be addressed.

Thanks
Nikhil

**Comment by nikhilrai1984** [comment]
Hi, Any updates here, Not sure whether I can expect any reply here or should we go try this out?
Thanks
Nikhil

**Comment by ro31337** [comment]
nice to have, not important or not current priority at the moment. Closing till the better time.
