### ISSUE TITLE
Broken link in Get Started Tutorial Step 3

### ISSUE THREAD

**Issue by fatcatdog** [ro31337/libretaxi#667]
In LibreTaxi's Getting Started Step 3, the suggested reading link to Firebase's rules/changing page is broken for me. 

I get a Firebase page that says this: 

"The project 'libretaxi-development' either does not exist, or myemailaddress@gmail.com doesn't have permission to view it.
TRY AGAIN"

**Comment by kris-cote** [comment]
Have you created the database in Firebase yet?

**Comment by fatcatdog** [comment]
Yup I created a firebase database, 

I still am getting errors, i suspect im setting my environment up incorrectly

**Comment by ro31337** [comment]
`libretaxi-development` should be replaced with your own name. For example, `fatcatdog-development`. It's something you specify. If you have errors, please post them here. Full errors, screenshots, steps to reproduce, etc. I'll try to help

**Comment by fatcatdog** [comment]
![screen shot 2017-12-07 at 10 46 19 pm](https://user-images.githubusercontent.com/25831976/33750231-7fa28282-dba0-11e7-9486-03b474af7f2b.png)

**Comment by fatcatdog** [comment]
my current errors... 

trying to install dependencies

**Comment by fatcatdog** [comment]
![screen shot 2017-12-07 at 10 48 53 pm](https://user-images.githubusercontent.com/25831976/33750321-2e315364-dba1-11e7-91c0-c123d9d6240a.png)

**Comment by fatcatdog** [comment]
Not sure what you are referring to here, do you mean my firebase project
should be titled "fatcatdog-development" in firebase?

**Comment by ro31337** [comment]
WARN - is just a warning, you can ignore now.

To fix the error when you run `npm test` you need to run `npm install` before (you need to do it one time, if you run it multiple times - it's also ok).

**Comment by fatcatdog** [comment]
![screen shot 2017-12-07 at 11 03 43 pm](https://user-images.githubusercontent.com/25831976/33750608-2e2c87b0-dba3-11e7-8270-8ffa2682b6a0.png)

**Comment by fatcatdog** [comment]
![screen shot 2017-12-07 at 11 06 26 pm](https://user-images.githubusercontent.com/25831976/33750653-722b5360-dba3-11e7-93c1-1d2954b2700a.png)

**Comment by ro31337** [comment]
what's the output of `npm -v` and `node -v`?

**Comment by fatcatdog** [comment]
![screen shot 2017-12-07 at 11 19 07 pm](https://user-images.githubusercontent.com/25831976/33750937-29ee3412-dba5-11e7-94a9-f441686f4557.png)

**Comment by ro31337** [comment]
it should be OK. Can you try removing your already installed modules `rm -rf ./node_modules/` (dangerous, be careful) and `npm install` again?

**Comment by fatcatdog** [comment]
passed tests, will spend more time tomorrow, thanks for help 👍

**Comment by ro31337** [comment]
I'm happy I was helpful. If you'll find documentation confusing, please improve - you will help other people trying to install their own libretaxi instance.
