### ISSUE TITLE
Interesting app but no way to keep up

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ro31337/libretaxi#669]
Hi,
great app but I have a small isue, I've been trying for some time to find your blog/rss feed/newsletter and so far I didn't find anything. So either you don't have any, or it's too hidden for most curious people. You have a great project but there doesn't seem to be a way to stay up to date on your changes and so on.

What do you think of that ? :)

**Comment by ro31337** [comment]
twitter - libretaxiorg

thanks
