### ISSUE TITLE
After I run npm run build-production && npm run telegram-production, i get error: "409 Conflict: terminated by other long poll or webhook"

### ISSUE THREAD

**Issue by fatcatdog** [ro31337/libretaxi#672]
![screen shot 2017-12-10 at 11 54 50 am](https://user-images.githubusercontent.com/25831976/33807246-92fabe5a-dda1-11e7-8f85-e21e70d66210.png)

**Comment by fatcatdog** [comment]
Should i not be running: npm run build-production && npm run telegram-production ?

if i skip this step, i don't get any errors, i see messages incoming from a user into telegram cli in terminal ("recieved message "hey how are you" from telegram_xxxx), but there is no communication aside from "libretaxi bot is typing" in telegram app

**Comment by ro31337** [comment]
Unfortunately I don't see which command are you running. Can you provide the full text log?

For development purposes I use `npm run telegram`, I would start with this comman

**Comment by ro31337** [comment]
I assume this been resolved

**Comment by fatcatdog** [comment]
Sorry I didn't comment again, some setting/I don't know what was wrong with my Mac was preventing lots of applications from running on my machine, I factory rebooted the Mac and havn't had problems since. 

You da man Roman!

**Comment by ro31337** [comment]
Yay! Glad to hear that
