### ISSUE TITLE
Monetizing idea

### ISSUE THREAD

**Issue by hdavy2002** [ro31337/libretaxi#679]
Would it be possible to insert Google ad via Telegram bot.  Something like, when the bot is chatting, after every few lines of chat a small Google ad gets inserted as part of the chat, and it gets scrolled up. I mean, it should look like a message. Or someone can create a custom telegram app and wrap google ad on it.  Then we can use that app as default for libretaxi. Hope I am making sense. Ad revenues should pay for servers and bandwidth.

**Comment by ro31337** [comment]
I think technically it's not possible. Also, monetization is not the priority of this project. Also, there is no servers, there is only one server. Paying out of the pocket, though.

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
