### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by osmoc** [ro31337/libretaxi#680]
https://f-droid.org/ is the main channel for open source android projects. Adding libretaxi there would greatly help to increase user base.

**Comment by ro31337** [comment]
@osmoc can you do that?

**Comment by osmoc** [comment]
I can file a request, but I'm not familiar enough with libretaxi code to decide if it fits with https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by ro31337** [comment]
> The software should use its own unique Android package ID

There is no such ID. App can't be submitted

**Comment by osmoc** [comment]
> There is no such ID.

That's surprising but it shouldn't discourage you: just pick one you like. Smth like `applicationId "org.libretaxi"` would do the trick. Essentially it's just a string uniquely identifying your app which you select yourself. General convention is to use associated URL. See https://developer.android.com/studio/build/application-id.html for example.

Hence, I think this ticket should be re-opened.

**Comment by ro31337** [comment]
That's not possible, because the app is not Android application. It works on Android, thru Telegram. One day we'll release native app and I'll reopen this issue.
