### ISSUE TITLE
Send voice message to share destination

### ISSUE THREAD

**Issue by karimgoza** [ro31337/libretaxi#683]
I come from a country where most of the population is illiterate.
But most of these people use whatsapp voicemessage to communicate.
I would like to know if it would be possible after choosing the type of vehicle we want (easy to choose with the icons) that the customer send the destination and the desired amount through a voice message.

The driver will then listen and if ok will send his number.

French speaking country so sorry for bad english

**Comment by ro31337** [comment]
Not important or not current priority at the moment. Closing till the better time.
