### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by marcelnakamine** [ro31337/libretaxi#685]
An alternative to have libretaxi up and running with Docker solution.

**Comment by nurazhar** [comment]
he already answered https://github.com/ro31337/libretaxi/blob/master/doc/GETTING-STARTED.md#still-have-issues

**Comment by dnk8n** [comment]
This is such a great find. I can work on adding Docker support. Will add progress here.

Off-topic: Where can I talk about developing for this project. I had this exact idea and want to implement it in a rural South African community with poor internet connection. I was hoping to build a self-hosted solution that could integrate with a wider network (Like Peertube for example). Also want to incorporate interactions with USSD.

**Comment by dnk8n** [comment]
This is such a great find. I can work on adding Docker support. Will add progress here.

Off-topic: Where can I talk about developing for this project. I had this exact idea and want to implement it in a rural South African community with poor internet connection. I was hoping to build a self-hosted solution that could integrate with a wider network (Like Peertube for example). Also want to incorporate interactions with USSD.

**Comment by ro31337** [comment]
Cool, you can join our chat by following the link https://telegram.me/libretaxi
