### ISSUE TITLE
problems running the application

### ISSUE THREAD

**Issue by Danielagarcia1309** [ro31337/libretaxi#686]
I have done all the steps to start with the application, but I have somecommenders to run telegram. It should be noted that I am in the Linux operating system, when I run npm run telegram I get this, I do not know if it's a problem...

> libretaxi@0.1.0 telegram-production /home/seidor/Documentos/libretaxi
> node ./build/app-telegram.js

node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:541:32
OK telegram bot is waiting for messages...
(node:6065) Warning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit

And it stays there thinking! has passed all the tests correctly, now, how do I start the application?

Thank you for the attention I would appreciate your response

**Comment by ro31337** [comment]
Will reopen when I have time
