### ISSUE TITLE
Consider a federated decentralized network architecture

### ISSUE THREAD

**Issue by dnk8n** [ro31337/libretaxi#692]
What is done already is great but will not be adopted in areas with high mistrust and opportunistic crime. [This article does a decent job introducing the concept of a federated network](http://networkcultures.org/unlikeus/resources/articles/what-is-a-federated-network/). I think it could be a good solution to ensuring trust.

Building support for something like riot.im is a good start. It is open-source too and allows home servers to be self-hosted.

**Comment by dnk8n** [comment]
> Is there a federated protocol you're thinking of specifically @dnk8n? I'm thinking of starting an "uber-for-x" open source project and wanted to see if there was a good federation paradigm out there which is how I found this issue!

Not thinking about anything specific at this stage. Not had enough time to dedicate to problem solving this one. Please post any ideas as and when you arrive on them. Also, feel free to get in touch if you feel like explaining uber-for-x idea!

**Comment by hferee** [comment]
It would seem that using something like XMPP for the transport layer would solve this, as well as #497.
