### ISSUE TITLE
How to install on my phone

### ISSUE THREAD

**Issue by jfoclpf** [ro31337/libretaxi#693]
First of all, thanks a lot for this great project, this is surely the future, directly transferring the money from client to provider without paying third party loan sharks. 

Off-topic apart, and concerning the app, how can I simply install the app on my android for an overview on the user-side? I clicked on my phone the [download button](https://telegram.me/libretaxi_bot) and it doesn't work.  Do I need to have telegram app installed?

Why is libretaxi not yet in Playstore?

Again, congrats for the great promising project! This is surely the future!

**Comment by n-kolosov** [comment]
Hello! LibreTaxi is a telegram-bot. You need to install telegram app before using it.
Best regards, Nikolay

**Comment by jfoclpf** [comment]
Thank you
