### ISSUE TITLE
Integrations with Odoo for Small Businesses operating fleets

### ISSUE THREAD

**Issue by arjunvenkatraman** [ro31337/libretaxi#694]
Hi, I'm currently testing out LibreTaxi for use by small businesses in India who operate small fleets of taxis (in competition with Uber & Ola). The current client I am dev-ing for is a company that operates cabs driven by women targeted primarily at  women passengers. They require the system to be integrated with a CRM/Invoicing platform to track their fleet better. I'm very new to node as a platform, so was curious to see if any work has been done on these lines at all or if anyone has suggestions!
Fork here - https://github.com/hackergram/libretaxi-crm

**Comment by ro31337** [comment]
Hi, there is no CRM integration out of the box, and we're not planning at the moment to add any. You must  do it yourself. Also, no any suggestions, because I'm unfamiliar with CRMs in general. I will close the issue, but if you have comments, feel free to post them
