### ISSUE TITLE
Add Kurdish language

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#697]
There is a PR waiting for it https://github.com/ro31337/libretaxi/pull/696

Create branch, merge changes into this branch (change base), add language from this change: https://github.com/ro31337/libretaxi/pull/696/files/56d48d1905a26333ea6efa86a907c7f1053cad04..f6d55aa5e9189e0611b5fa4059aa568a6bbabdc8

Make sure tests are green and merge into master.

**Comment by ro31337** [comment]
Done, changes have been deployed to host.

**Comment by yasin4731** [comment]
Thanks a lot.
