### ISSUE TITLE
Fix security issues

### ISSUE THREAD

**Issue by ro31337** [ro31337/libretaxi#710]
![image](https://user-images.githubusercontent.com/1477672/51721255-d8754480-2005-11e9-9f2e-e741177c807a.png)

^^^ Here is the screenshot of security issues. They need to be addressed.

**Comment by ro31337** [comment]
@swember you wanna look at this one? Fix them, make sure all tests are OK. Don't forget to keep the same convention while working on commits, like: `#710 Fix blabla`

I can find something else (more interesting) if this one looks boring.

**Comment by ro31337** [comment]
![image](https://user-images.githubusercontent.com/1477672/51758556-d4cfd500-207a-11e9-9e9a-6600dd2e5719.png)

**Comment by swember** [comment]
@ro31337 sure, thank you.
