### ISSUE TITLE
Max Listener Error

### ISSUE THREAD

**Issue by BhaveshPrince** [ro31337/libretaxi#711]
(node:8272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setM
axListeners() to increase limit

**Comment by BhaveshPrince** [comment]
Hello Sir,

Thanks for response.

Please let me know about how to fix this problem step by step.

**Comment by BhaveshPrince** [comment]
I cannot run a project on localhost.please give me the solution.

**Comment by ro31337** [comment]
> I cannot run a project on localhost.please give me the solution.

Solution: drink some beer

But honestly, if you have error, respect the author and post some error message at least ;)
