### ISSUE TITLE
NPM tests failed

### ISSUE THREAD

**Issue by aldeiart** [ro31337/libretaxi#720]
Hi, I tried to install the libretaxi om my server, but on the npm test, I have some errors... anyone can help to understand this and fix?

> libretaxi@0.1.0 test /var/www/meleva
> npm run lint && npm run ava ./test/before-all.js && npm run ava

> libretaxi@0.1.0 lint /var/www/meleva
> eslint src test

> /var/www/meleva/src/actions/menu/passenger/request-price.js
>   28:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved

> /var/www/meleva/src/conditions/around.js
>   20:22  error  Unable to resolve path to module 'geopoint'  import/no-unresolved

> /var/www/meleva/src/firebase-db.js
>   19:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved

> /var/www/meleva/src/response-handlers/cli/interrupt-prompt-response-handler.js
>   20:22  error  Unable to resolve path to module 'inquirer'  import/no-unresolved

> /var/www/meleva/src/response-handlers/cli/options-response-handler.js
>   20:22  error  Unable to resolve path to module 'inquirer'  import/no-unresolved

> /var/www/meleva/src/response-handlers/cli/request-location-response-handler.js
>   20:22  error  Unable to resolve path to module 'inquirer'  import/no-unresolved

> /var/www/meleva/src/response-handlers/cli/request-phone-response-handler.js
>  20:22  error  Unable to resolve path to module 'inquirer'  import/no-unresolved

> /var/www/meleva/src/response-handlers/cli/request-user-input-response-handler.js
>   20:22  error  Unable to resolve path to module 'inquirer'  import/no-unresolved

> /var/www/meleva/src/response-handlers/update-location-response-handler.js
>   24:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved

> /var/www/meleva/src/tools/purge-stale-orders.js
>   20:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved

> ✖ 10 problems (10 errors, 0 warnings)

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libretaxi@0.1.0 lint: `eslint src test`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the libretaxi@0.1.0 lint script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ro31337** [comment]
Seems like you didn't do `npm install`
