### ISSUE TITLE
Yet npm install errors

### ISSUE THREAD

**Issue by aldeiart** [ro31337/libretaxi#721]
@ro31337, you closed the issue, but its not resolved, and if you could help with this, I would appreciate so much

>Seems like you didn't do `npm install`

>_Originally posted by @ro31337 in https://github.com/ro31337/libretaxi/issues/720#issuecomment-546703915_

I do.
And I do `npm install --save eslint-config-airbnb` too, because i having this issues before:

npm test

> libretaxi@0.1.0 test /var/www/meleva
> npm run lint && npm run ava ./test/before-all.js && npm run ava

> libretaxi@0.1.0 lint /var/www/meleva
> eslint src test

> Oops! Something went wrong! :(

> ESLint: 6.6.0.

> ESLint couldn't find the config "airbnb/base" to extend from. Please check that the name of the config is correct.

> The config "airbnb/base" was referenced from the config file in "/var/www/meleva/.eslintrc".

> If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.

> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! libretaxi@0.1.0 lint: `eslint src test`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the libretaxi@0.1.0 lint script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> npm ERR! A complete log of this run can be found in:

And I search on Google, and find the suggestion to do this command, but this make more errors appears

**Comment by aldeiart** [comment]
I reinstall from the beginning, and now appears only this errors

> /var/www/meleva/src/actions/menu/passenger/request-price.js
>   28:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved
> 
> /var/www/meleva/src/firebase-db.js
>   19:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved
> 
> /var/www/meleva/src/response-handlers/update-location-response-handler.js
>   24:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved
> 
> /var/www/meleva/src/tools/purge-stale-orders.js
>   20:22  error  Unable to resolve path to module 'firebase-admin'  import/no-unresolved
> 
> ✖ 4 problems (4 errors, 0 warnings)

**Comment by aldeiart** [comment]
and Yes, I do `npm install`

**Comment by ro31337** [comment]
Yes, seems for unknown reason build is failing now. Npm and Node.js infrastructure is a total shit show as of today, it was OK yesterday, but now it just doesn't install anything.

https://travis-ci.org/ro31337/libretaxi/ is also failing

Can't do anything, sorry. High rental prices in San Francisco discourage me from doing any help/open source work without funding. Dreaming about leaving the shitty place. Gone to pay my bills. Good luck with that.

**Comment by aldeiart** [comment]
OK, I undesrtand agreed with your word... thanks anyway.

**Comment by aldeiart** [comment]
I resolved by deleting the node_modules and install by 
> meteor npm install
