### ISSUE TITLE
Init Bot api failed

### ISSUE THREAD

**Issue by ChanXxb** [ro31337/libretaxi#734]
init bot api failed
i got  my token from botFather，but tgbotapi.NewBotAPI（） panic..

connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

（Docker service started  correctly ，
accessing the api.telegram.org/my_token    correctly）

**Comment by ro31337** [comment]
Please reopen ticket with more details. Now it's quite ambiguous, problem is not clear.
