### ISSUE TITLE
Website certificate expired 

### ISSUE THREAD

**Issue by onkoe** [ro31337/libretaxi#744]
Hello! This has little to do with the project itself, but as of five days ago, the website certificate for libretaxi.org has expired. It would be a good idea to extend it to keep credibility and security. I have attached a screenshot of the issue below. Thanks for the awesome service!  http://imgur.com/a/mWYTYNN

**Comment by ro31337** [comment]
Fixed.

For reference:

```
cd ~/work/libretaxi-www2
sudo docker rm libretaxi-www
sudo docker run --name libretaxi-www --label-file ./labels -v $(pwd)/Caddyfile:/etc/Caddyfile -p 80:80 -p 443:443 -e "CADDYPATH=/etc/caddycerts" -e ACME_AGREE=true -v $HOME/.caddy:/etc/caddycerts --network hardwaresecurity_default -d abiosoft/caddy
```
