### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by theRAGEhero** [ro31337/libretaxi#745]
Hello and thank you for your work.

I'm trying the LibreTaxi telegram bot (not selfhosted) but I'm not able to make it works. The bot doesn't reply.
Am I doing something wrong or the bot is not working?

Thank you

**Comment by ro31337** [comment]
It works. You can try this out https://t.me/libretaxi_bot

Not sure what was the particular issue with the scenario you described, there can be many explanations. If you have more details, feel free to open a new issue.

**Comment by theRAGEhero** [comment]
Thank you for your reply.
Unfortunately it doesn't reply...

![image](https://user-images.githubusercontent.com/39453005/145453696-6bafe523-831d-4ebb-a7d3-10ea0a5bddc1.png)
